"""added type field in actuators and sensors

Revision ID: 7ef088c6d34e
Revises: 4e7de744cf33
Create Date: 2024-06-11 01:29:03.337477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef088c6d34e'
down_revision = '4e7de744cf33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actuator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=80), nullable=False))

    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('actuator', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
